import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";

import { cachedClient } from "../../sanity/lib/client";
import { siteConfigQuery } from "../../sanity/lib/queries";

const inter = Inter({ subsets: ["latin"] });

export async function generateMetadata(){ 
  const siteConfig = await cachedClient(siteConfigQuery)
  return {
    title: siteConfig.title,
    description: siteConfig.description,
  }
}

// export const metadata = {
//   title: "The Fish Recipes",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}